export interface Env { DB: D1Database; FAMILY_INVITE_CODE: string; ANTHROPIC_API_KEY: string; SESSION_SECRET: string; CLAUDE_MODEL?: string }
type User = { id: string; login_id: string };
const json = (data: unknown, status = 200, headers: HeadersInit = {}) => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...headers } });
const err = (status: number, message: string) => json({ error: message }, status);
const DATE = /^\d{4}-\d{2}-\d{2}$/, TIME = /^([01]\d|2[0-3]):[0-5]\d$/;
const encoder = new TextEncoder();
const now = () => new Date().toISOString();
const uuid = () => crypto.randomUUID();
async function digest(value: string) { return [...new Uint8Array(await crypto.subtle.digest('SHA-256', encoder.encode(value)))].map(x => x.toString(16).padStart(2, '0')).join(''); }
async function passwordHash(password: string, salt = crypto.getRandomValues(new Uint8Array(16))) {
  const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', hash: 'SHA-256', salt, iterations: 310000 }, key, 256);
  return `pbkdf2$310000$${btoa(String.fromCharCode(...salt))}$${btoa(String.fromCharCode(...new Uint8Array(bits)))}`;
}
async function passwordMatches(password: string, stored: string) { const [, , salt] = stored.split('$'); return salt ? timingSafe(await passwordHash(password, Uint8Array.from(atob(salt), c => c.charCodeAt(0))), stored) : false; }
function timingSafe(a: string, b: string) { if (a.length !== b.length) return false; let result = 0; for (let i = 0; i < a.length; i++) result |= a.charCodeAt(i) ^ b.charCodeAt(i); return result === 0; }
function cookie(token: string) { return `hoiku_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`; }
function cookieValue(request: Request) { return request.headers.get('cookie')?.match(/(?:^|;\s*)hoiku_session=([^;]+)/)?.[1]; }
function validOrigin(request: Request) { const origin = request.headers.get('origin'); return !origin || origin === new URL(request.url).origin; }
async function limited(env: Env, key: string) { const stamp = Date.now(), row = await env.DB.prepare('SELECT window_started_at, attempts FROM rate_limits WHERE key=?').bind(key).first<{window_started_at:number;attempts:number}>(); const attempts = row && stamp - row.window_started_at < 900000 ? row.attempts + 1 : 1; await env.DB.prepare('INSERT INTO rate_limits(key,window_started_at,attempts) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET window_started_at=excluded.window_started_at,attempts=excluded.attempts').bind(key, attempts === 1 ? stamp : row!.window_started_at, attempts).run(); return attempts > 10; }
async function userFor(request: Request, env: Env): Promise<User | null> { const token = cookieValue(request); if (!token) return null; const hash = await digest(token + env.SESSION_SECRET); return env.DB.prepare('SELECT users.id, users.login_id FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=? AND sessions.expires_at>? AND users.disabled_at IS NULL').bind(hash, now()).first<User>(); }
async function body(request: Request) { try { return await request.json<Record<string, unknown>>(); } catch { return null; } }
function date(value: unknown) { return typeof value === 'string' && DATE.test(value) ? value : null; }
async function locked(env: Env, day: string) { return !!(await env.DB.prepare('SELECT locked FROM day_locks WHERE date=?').bind(day).first<{locked:number}>())?.locked; }

export default { async fetch(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url); if (!url.pathname.startsWith('/api/')) return new Response('Not found', { status: 404 });
  if (request.method !== 'GET' && !validOrigin(request)) return err(403, 'Invalid request origin.');
  const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
  if (url.pathname === '/api/auth/register' && request.method === 'POST') { if (await limited(env, `register:${ip}`)) return err(429, 'Please wait and try again.'); const b = await body(request); const login = typeof b?.login_id === 'string' ? b.login_id.trim() : ''; const pw = typeof b?.password === 'string' ? b.password : ''; if (!b || !timingSafe(String(b.invite_code || ''), env.FAMILY_INVITE_CODE) || !/^[a-zA-Z0-9_-]{3,32}$/.test(login) || pw.length < 12) return err(400, 'Registration details are invalid.'); const count = await env.DB.prepare('SELECT COUNT(*) AS n FROM users WHERE disabled_at IS NULL').first<{n:number}>(); if ((count?.n || 0) >= 2) return err(403, 'Registration is unavailable.'); try { await env.DB.prepare('INSERT INTO users(id,login_id,password_hash) VALUES(?,?,?)').bind(uuid(), login, await passwordHash(pw)).run(); return json({ ok: true }, 201); } catch { return err(409, 'Registration is unavailable.'); } }
  if (url.pathname === '/api/auth/login' && request.method === 'POST') { if (await limited(env, `login:${ip}`)) return err(429, 'Please wait and try again.'); const b = await body(request); const login = typeof b?.login_id === 'string' ? b.login_id.trim() : ''; const pw = typeof b?.password === 'string' ? b.password : ''; const account = await env.DB.prepare('SELECT id,password_hash FROM users WHERE login_id=? AND disabled_at IS NULL').bind(login).first<{id:string;password_hash:string}>(); if (!account || !await passwordMatches(pw, account.password_hash)) return err(401, 'Login ID or password is incorrect.'); const token = crypto.randomUUID() + crypto.randomUUID(); await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(await digest(token + env.SESSION_SECRET), account.id, new Date(Date.now()+604800000).toISOString()).run(); return json({ ok: true }, 200, { 'set-cookie': cookie(token) }); }
  if (url.pathname === '/api/auth/logout' && request.method === 'POST') { const t = cookieValue(request); if (t) await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(await digest(t + env.SESSION_SECRET)).run(); return json({ ok:true }, 200, { 'set-cookie': 'hoiku_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0' }); }
  const user = await userFor(request, env); if (!user) return err(401, 'Authentication required.'); if (url.pathname === '/api/auth/me') return json({ user: { login_id: user.login_id } });
  const day = date(url.searchParams.get('date')); if (url.pathname === '/api/day' && request.method === 'GET') { if (!day) return err(400,'Invalid date.'); const [events, diary, lock] = await env.DB.batch([env.DB.prepare('SELECT id,date,category,start_time AS start,end_time AS end,memo FROM events WHERE date=? ORDER BY start_time,created_at').bind(day), env.DB.prepare('SELECT text,timeline,weather FROM diaries WHERE date=?').bind(day), env.DB.prepare('SELECT locked FROM day_locks WHERE date=?').bind(day)]); return json({ events: events.results, diary: diary.results[0] || null, locked: !!lock.results[0]?.locked }); }
  if (url.pathname === '/api/events' && request.method === 'POST') { const b=await body(request), d=date(b?.date), start=typeof b?.start==='string'&&TIME.test(b.start)?b.start:null, end=b?.end === '' || b?.end == null ? null : typeof b?.end==='string'&&TIME.test(b.end)?b.end:null; if (!d||!start||!end&&b?.end||typeof b?.category!=='string'||typeof b?.memo!=='string'||b.memo.length>2000) return err(400,'Invalid event.'); if(await locked(env,d)) return err(423,'This day is locked.'); const id=typeof b.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(b.id)?b.id:uuid(); await env.DB.prepare('INSERT INTO events(id,date,category,start_time,end_time,memo,created_by,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,d,b.category,start,end,b.memo,user.id,now()).run(); return json({ id },201); }
  if (url.pathname.startsWith('/api/events/') && request.method === 'DELETE') { const id=url.pathname.split('/').pop()!; const event=await env.DB.prepare('SELECT date FROM events WHERE id=?').bind(id).first<{date:string}>(); if(!event) return json({ok:true}); if(await locked(env,event.date)) return err(423,'This day is locked.'); await env.DB.prepare('DELETE FROM events WHERE id=?').bind(id).run(); return json({ok:true}); }
  if (url.pathname === '/api/weather' && request.method === 'PUT') { const b=await body(request),d=date(b?.date); if(!d||typeof b?.weather!=='string')return err(400,'Invalid weather.'); if(await locked(env,d))return err(423,'This day is locked.'); await env.DB.prepare("INSERT INTO diaries(date,text,timeline,weather,generated_by,updated_at) VALUES(?,?,?, ?,?,?) ON CONFLICT(date) DO UPDATE SET weather=excluded.weather,updated_at=excluded.updated_at").bind(d,'','[]',b.weather,user.id,now()).run(); return json({ok:true}); }
  if (url.pathname === '/api/locks' && request.method === 'PUT') { const b=await body(request),d=date(b?.date); if(!d||typeof b?.locked!=='boolean')return err(400,'Invalid lock.'); await env.DB.prepare('INSERT INTO day_locks(date,locked,updated_by,updated_at) VALUES(?,?,?,?) ON CONFLICT(date) DO UPDATE SET locked=excluded.locked,updated_by=excluded.updated_by,updated_at=excluded.updated_at').bind(d,b.locked?1:0,user.id,now()).run(); return json({ok:true}); }
  if (url.pathname === '/api/diaries/generate' && request.method === 'POST') { const b=await body(request),d=date(b?.date); if(!d)return err(400,'Invalid date.'); if(await limited(env,`generate:${user.id}`))return err(429,'Please wait and try again.'); if(await locked(env,d))return err(423,'This day is locked.'); const events=(await env.DB.prepare('SELECT category,start_time,end_time,memo FROM events WHERE date=? ORDER BY start_time').bind(d).all()).results; const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:env.CLAUDE_MODEL||'claude-sonnet-4-20250514',max_tokens:1000,messages:[{role:'user',content:`${d}の保育記録を温かい日本語の日記にしてください。記録: ${JSON.stringify(events)}`}]})}); if(!response.ok)return err(502,'Diary generation is temporarily unavailable.'); const result=await response.json<any>(); const text=result.content?.[0]?.text; if(typeof text!=='string')return err(502,'Diary generation is temporarily unavailable.'); await env.DB.prepare('INSERT INTO diaries(date,text,timeline,weather,generated_by,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(date) DO UPDATE SET text=excluded.text,timeline=excluded.timeline,generated_by=excluded.generated_by,updated_at=excluded.updated_at').bind(d,text,JSON.stringify(events),(await env.DB.prepare('SELECT weather FROM diaries WHERE date=?').bind(d).first<any>())?.weather||null,user.id,now()).run(); return json({text,timeline:events}); }
  return err(404,'Not found.');
} };
