export interface Env { DB: D1Database; FAMILY_INVITE_CODE: string; ANTHROPIC_API_KEY: string; SESSION_SECRET: string; CLAUDE_MODEL?: string; ALLOWED_ORIGINS?: string }
type User = { id: string; login_id: string };
const CATEGORIES = new Set(['breakfast','lunch','dinner','snack','wakeup','nap','bedtime','play','bath','poop','temp','other']);
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const TIME = /^([01]\d|2[0-3]):[0-5]\d$/;
const ID = /^[a-zA-Z0-9_-]{1,80}$/;
const encoder = new TextEncoder();
const now = () => new Date().toISOString();
const uuid = () => crypto.randomUUID();
const json = (data: unknown, status = 200, headers: HeadersInit = {}) => new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...headers } });
const err = (status: number, message = 'Request failed.') => json({ error: message }, status);
async function digest(value: string) { return [...new Uint8Array(await crypto.subtle.digest('SHA-256', encoder.encode(value)))].map(x => x.toString(16).padStart(2, '0')).join(''); }
async function passwordHash(password: string, salt = crypto.getRandomValues(new Uint8Array(16))) { const key = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', hash: 'SHA-256', salt, iterations: 310000 }, key, 256); return `pbkdf2$310000$${btoa(String.fromCharCode(...salt))}$${btoa(String.fromCharCode(...new Uint8Array(bits)))}`; }
async function passwordMatches(password: string, stored: string) { const [, , salt] = stored.split('$'); return salt ? timingSafe(await passwordHash(password, Uint8Array.from(atob(salt), c => c.charCodeAt(0))), stored) : false; }
function timingSafe(a: string, b: string) { if (a.length !== b.length) return false; let result = 0; for (let i = 0; i < a.length; i++) result |= a.charCodeAt(i) ^ b.charCodeAt(i); return result === 0; }
function cookie(token: string, maxAge = 604800) { return `hoiku_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`; }
function cookieValue(request: Request) { return request.headers.get('cookie')?.match(/(?:^|;\s*)hoiku_session=([^;]+)/)?.[1]; }
function validDate(value: unknown) { if (typeof value !== 'string' || !DATE.test(value)) return null; const d = new Date(`${value}T00:00:00Z`); return d.toISOString().slice(0, 10) === value ? value : null; }
function validOrigin(request: Request, env: Env) { const origin = request.headers.get('origin'); if (!origin) return request.method === 'GET' || request.headers.get('sec-fetch-site') === 'same-origin'; const self = new URL(request.url).origin; const allowed = new Set([self, ...(env.ALLOWED_ORIGINS || '').split(',').map(x => x.trim()).filter(Boolean)]); return allowed.has(origin); }
async function readBody(request: Request) { if (Number(request.headers.get('content-length') || 0) > 16384) return null; try { const text = await request.text(); if (text.length > 16384) return null; return JSON.parse(text) as Record<string, unknown>; } catch { return null; } }
async function limited(env: Env, key: string, limit = 10) { const stamp = Date.now(), win = 900000; await env.DB.prepare("INSERT INTO rate_limits(key,window_started_at,attempts) VALUES(?,?,1) ON CONFLICT(key) DO UPDATE SET attempts=CASE WHEN ?-window_started_at<? THEN attempts+1 ELSE 1 END, window_started_at=CASE WHEN ?-window_started_at<? THEN window_started_at ELSE ? END").bind(key, stamp, stamp, win, stamp, win, stamp).run(); const row = await env.DB.prepare('SELECT attempts FROM rate_limits WHERE key=?').bind(key).first<{attempts:number}>(); return (row?.attempts || 0) > limit; }
async function userFor(request: Request, env: Env): Promise<User | null> { const token = cookieValue(request); if (!token) return null; const hash = await digest(token + env.SESSION_SECRET); return env.DB.prepare('SELECT users.id, users.login_id FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=? AND sessions.expires_at>? AND users.disabled_at IS NULL').bind(hash, now()).first<User>(); }
async function locked(env: Env, day: string) { return !!(await env.DB.prepare('SELECT locked FROM day_locks WHERE date=?').bind(day).first<{locked:number}>())?.locked; }
function cleanEvent(b: Record<string, unknown> | null) { const d = validDate(b?.date), start = typeof b?.start === 'string' && TIME.test(b.start) ? b.start : null, end = b?.end == null || b?.end === '' ? null : typeof b?.end === 'string' && TIME.test(b.end) ? b.end : undefined; const category = typeof b?.category === 'string' && CATEGORIES.has(b.category) ? b.category : null; const id = typeof b?.id === 'string' && ID.test(b.id) ? b.id : uuid(); const memo = typeof b?.memo === 'string' && b.memo.length <= 2000 ? b.memo : null; return d && start && end !== undefined && category && memo !== null ? { id, date: d, category, start, end, memo } : null; }
async function assertUnlocked(env: Env, day: string) { if (await locked(env, day)) throw err(423, 'This day is locked.'); }

export default { async fetch(request: Request, env: Env): Promise<Response> {
  try {
  const url = new URL(request.url); if (!url.pathname.startsWith('/api/')) return new Response('Not found', { status: 404 });
  if (request.method !== 'GET' && !validOrigin(request, env)) return err(403, 'Invalid request origin.');
  const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
  await env.DB.prepare('DELETE FROM sessions WHERE expires_at<=?').bind(now()).run(); await env.DB.prepare('DELETE FROM rate_limits WHERE window_started_at<?').bind(Date.now() - 86400000).run();
  if (url.pathname === '/api/auth/register' && request.method === 'POST') { if (await limited(env, `register:${ip}`)) return err(429, 'Please wait and try again.'); const b = await readBody(request); const login = typeof b?.login_id === 'string' ? b.login_id.trim() : ''; const pw = typeof b?.password === 'string' ? b.password : ''; if (!b || !timingSafe(String(b.invite_code || ''), env.FAMILY_INVITE_CODE) || !/^[a-zA-Z0-9_-]{3,32}$/.test(login) || pw.length < 12) return err(400, 'Registration details are invalid.'); try { await env.DB.prepare('INSERT INTO users(id,login_id,password_hash,active_slot) SELECT ?,?,?, COALESCE((SELECT MIN(slot) FROM account_slots WHERE slot NOT IN (SELECT active_slot FROM users WHERE disabled_at IS NULL)), -1) WHERE (SELECT COUNT(*) FROM users WHERE disabled_at IS NULL)<2').bind(uuid(), login, await passwordHash(pw)).run(); } catch { return err(409, 'Registration is unavailable.'); } const created = await env.DB.prepare('SELECT id FROM users WHERE login_id=? AND disabled_at IS NULL').bind(login).first(); return created ? json({ ok: true }, 201) : err(403, 'Registration is unavailable.'); }
  if (url.pathname === '/api/auth/login' && request.method === 'POST') { if (await limited(env, `login:${ip}`)) return err(429, 'Please wait and try again.'); const b = await readBody(request); const login = typeof b?.login_id === 'string' ? b.login_id.trim() : ''; const pw = typeof b?.password === 'string' ? b.password : ''; const account = await env.DB.prepare('SELECT id,password_hash FROM users WHERE login_id=? AND disabled_at IS NULL').bind(login).first<{id:string;password_hash:string}>(); if (!account || !await passwordMatches(pw, account.password_hash)) return err(401, 'Login ID or password is incorrect.'); const token = crypto.randomUUID() + crypto.randomUUID(); await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)').bind(await digest(token + env.SESSION_SECRET), account.id, new Date(Date.now()+604800000).toISOString()).run(); return json({ ok: true }, 200, { 'set-cookie': cookie(token) }); }
  if (url.pathname === '/api/auth/logout' && request.method === 'POST') { const t = cookieValue(request); if (t) await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(await digest(t + env.SESSION_SECRET)).run(); return json({ ok:true }, 200, { 'set-cookie': cookie('', 0) }); }
  const user = await userFor(request, env); if (!user) return err(401, 'Authentication required.'); if (url.pathname === '/api/auth/me') return json({ user: { login_id: user.login_id } });
  const day = validDate(url.searchParams.get('date'));
  if (url.pathname === '/api/day' && request.method === 'GET') { if (!day) return err(400,'Invalid date.'); const [events, diary, lock] = await env.DB.batch([env.DB.prepare('SELECT id,date,category,start_time AS start,end_time AS end,memo FROM events WHERE date=? ORDER BY start_time,created_at').bind(day), env.DB.prepare('SELECT text,timeline,weather FROM diaries WHERE date=?').bind(day), env.DB.prepare('SELECT locked FROM day_locks WHERE date=?').bind(day)]); return json({ events: events.results, diary: diary.results[0] || null, locked: !!lock.results[0]?.locked }); }
  if (url.pathname === '/api/events' && request.method === 'POST') { const ev = cleanEvent(await readBody(request)); if (!ev) return err(400,'Invalid event.'); await assertUnlocked(env, ev.date); const existing = await env.DB.prepare('SELECT created_by FROM events WHERE id=?').bind(ev.id).first<{created_by:string}>(); if (existing && existing.created_by !== user.id) return err(409, 'Event conflict.'); if (!existing) await env.DB.prepare('INSERT INTO events(id,date,category,start_time,end_time,memo,created_by,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(ev.id,ev.date,ev.category,ev.start,ev.end,ev.memo,user.id,now()).run(); return json({ id: ev.id }, existing ? 200 : 201); }
  if (url.pathname.startsWith('/api/events/') && request.method === 'DELETE') { const id=url.pathname.split('/').pop()!; if(!ID.test(id)) return err(400,'Invalid event.'); const event=await env.DB.prepare('SELECT date FROM events WHERE id=?').bind(id).first<{date:string}>(); if(!event) return json({ok:true}); await assertUnlocked(env,event.date); await env.DB.prepare('DELETE FROM events WHERE id=?').bind(id).run(); return json({ok:true}); }
  if (url.pathname === '/api/weather' && request.method === 'PUT') { const b=await readBody(request), d=validDate(b?.date), weather=typeof b?.weather === 'string' && b.weather.length <= 40 ? b.weather : null; if(!d||weather===null)return err(400,'Invalid weather.'); await assertUnlocked(env,d); await env.DB.prepare("INSERT INTO diaries(date,text,timeline,weather,generated_by,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(date) DO UPDATE SET weather=excluded.weather,updated_at=excluded.updated_at").bind(d,'','[]',weather,user.id,now()).run(); return json({ok:true}); }
  if (url.pathname === '/api/locks' && request.method === 'PUT') { const b=await readBody(request),d=validDate(b?.date); if(!d||typeof b?.locked!=='boolean')return err(400,'Invalid lock.'); await env.DB.prepare('INSERT INTO day_locks(date,locked,updated_by,updated_at) VALUES(?,?,?,?) ON CONFLICT(date) DO UPDATE SET locked=excluded.locked,updated_by=excluded.updated_by,updated_at=excluded.updated_at').bind(d,b.locked?1:0,user.id,now()).run(); return json({ok:true}); }
  if (url.pathname === '/api/diaries/save' && request.method === 'PUT') { const b=await readBody(request), d=validDate(b?.date), text=typeof b?.text==='string'&&b.text.length<=12000?b.text:null; if(!d||text===null)return err(400,'Invalid diary.'); await assertUnlocked(env,d); const timeline=typeof b?.timeline==='string'&&b.timeline.length<=20000?b.timeline:'[]'; await env.DB.prepare('INSERT INTO diaries(date,text,timeline,weather,generated_by,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(date) DO UPDATE SET text=excluded.text,timeline=excluded.timeline,updated_at=excluded.updated_at').bind(d,text,timeline,null,user.id,now()).run(); return json({ok:true}); }
  if (url.pathname === '/api/diaries/generate' && request.method === 'POST') { const b=await readBody(request),d=validDate(b?.date); if(!d)return err(400,'Invalid date.'); if(await limited(env,`generate:${user.id}`,5))return err(429,'Please wait and try again.'); await assertUnlocked(env,d); const child = typeof b?.child_name === 'string' && b.child_name.length <= 80 ? b.child_name : ''; const age = typeof b?.age === 'string' && b.age.length <= 40 ? b.age : ''; const diary = await env.DB.prepare('SELECT weather FROM diaries WHERE date=?').bind(d).first<{weather:string}>(); const events=(await env.DB.prepare('SELECT category,start_time,end_time,memo FROM events WHERE date=? ORDER BY start_time').bind(d).all()).results; const prompt = JSON.stringify({ date:d, child_name:child, age, weather:diary?.weather||null, events }); const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:env.CLAUDE_MODEL||'claude-sonnet-4-20250514',max_tokens:1000,messages:[{role:'user',content:`次の保育記録を温かい日本語の日記にしてください。${prompt}`}]})}); if(!response.ok)return err(502,'Diary generation is temporarily unavailable.'); const result=await response.json<any>(); const text=result.content?.[0]?.text; if(typeof text!=='string'||text.length>12000)return err(502,'Diary generation is temporarily unavailable.'); await assertUnlocked(env,d); await env.DB.prepare('INSERT INTO diaries(date,text,timeline,weather,generated_by,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(date) DO UPDATE SET text=excluded.text,timeline=excluded.timeline,generated_by=excluded.generated_by,updated_at=excluded.updated_at').bind(d,text,JSON.stringify(events),diary?.weather||null,user.id,now()).run(); return json({text,timeline:events}); }
  return err(404,'Not found.');
  } catch (e) { if (e instanceof Response) return e; return err(500, 'Request failed.'); }
} };
